### ISSUE TITLE
是否考虑去掉或替换题目名中的特殊字符，避免在Windows环境下Clone出现的问题

### ISSUE THREAD

**Issue by LyleMi** [ctf-wiki/ctf-challenges#41]
在Windows中，``<>,/,\,|,:,"",*,?`` 等符号不能在文件名中出现，使得在clone时 ``2015广州强网杯-爆破?`` 这样的题目名会导致clone出错。

能不能考虑把这些字符替换为对应的中文字符来避开这个问题或者替换掉这些无效字符？如果这个方式ok的话我之后提交一个相应的PR？

**Comment by iromise** [comment]
可以，没有问题，你提交 PR 吧。建议题目以 `-` 分割。
